### ISSUE TITLE
Suspect keyword issue in hadoop-fundamentals/hive/log_data/create_apache_log_table.sql

### ISSUE THREAD

**Issue by zmz0305** [bbengfort/hadoop-fundamentals#12]
When executing this file, it throws
```FailedPredicateException(identifier,{useSQL11ReservedKeywordsForIdentifier()}?)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.identifier(HiveParser_IdentifiersParser.java:11898)
	at org.apache.hadoop.hive.ql.parse.HiveParser.identifier(HiveParser.java:51813)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameType(HiveParser.java:42051)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeOrPKOrFK(HiveParser.java:42308)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeOrPKOrFKList(HiveParser.java:37966)
	at org.apache.hadoop.hive.ql.parse.HiveParser.createTableStatement(HiveParser.java:5259)
	at org.apache.hadoop.hive.ql.parse.HiveParser.ddlStatement(HiveParser.java:2763)
	at org.apache.hadoop.hive.ql.parse.HiveParser.execStatement(HiveParser.java:1756)
	at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1178)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:204)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:166)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:444)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1242)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1384)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1171)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1161)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:232)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:183)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:399)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:335)
	at org.apache.hadoop.hive.cli.CliDriver.processReader(CliDriver.java:429)
	at org.apache.hadoop.hive.cli.CliDriver.processFile(CliDriver.java:445)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:748)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:714)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
FAILED: ParseException line 6:3 Failed to recognize predicate 'user'. Failed rule: 'identifier' in column specification
```

It seems that the word "user" is a reserved word for SQL. It works after I changed "user" into "user1".

**Comment by bbengfort** [comment]
Awesome, thanks for the note; I'll let folks know if they have similar problems.
