### ISSUE TITLE
sales.py does not work as shown in video on the vmdk

### ISSUE THREAD

**Issue by ghost** [bbengfort/hadoop-fundamentals#7]
looks like the vmdk currently available does not seem to work on a few issues.  here's the latest i've found.  any way you could publish the one you used to create the course?  thanks in advance!

student@hadoop:~/Projects/hadoop-fundamentals/spark$ spark-submit sales.py 
Spark assembly has been built with Hive, including Datanucleus jars on classpath
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/07/08 10:46:03 WARN Utils: Your hostname, hadoop resolves to a loopback address: 127.0.1.1; using 192.168.59.131 instead (on interface eth0)
16/07/08 10:46:03 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
16/07/08 10:46:03 INFO SecurityManager: Changing view acls to: student,
16/07/08 10:46:03 INFO SecurityManager: Changing modify acls to: student,
16/07/08 10:46:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(student, ); users with modify permissions: Set(student, )
16/07/08 10:46:04 INFO Slf4jLogger: Slf4jLogger started
16/07/08 10:46:04 INFO Remoting: Starting remoting
16/07/08 10:46:04 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.59.131:60725]
16/07/08 10:46:04 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriver@192.168.59.131:60725]
16/07/08 10:46:04 INFO Utils: Successfully started service 'sparkDriver' on port 60725.
16/07/08 10:46:04 INFO SparkEnv: Registering MapOutputTracker
16/07/08 10:46:04 INFO SparkEnv: Registering BlockManagerMaster
16/07/08 10:46:05 INFO DiskBlockManager: Created local directory at /tmp/spark-local-20160708104605-73f8
16/07/08 10:46:05 INFO Utils: Successfully started service 'Connection manager for block manager' on port 57473.
16/07/08 10:46:05 INFO ConnectionManager: Bound socket to port 57473 with id = ConnectionManagerId(192.168.59.131,57473)
16/07/08 10:46:05 INFO MemoryStore: MemoryStore started with capacity 267.3 MB
16/07/08 10:46:05 INFO BlockManagerMaster: Trying to register BlockManager
16/07/08 10:46:05 INFO BlockManagerMasterActor: Registering block manager 192.168.59.131:57473 with 267.3 MB RAM
16/07/08 10:46:05 INFO BlockManagerMaster: Registered BlockManager
16/07/08 10:46:05 INFO HttpFileServer: HTTP File server directory is /tmp/spark-01df407f-52ad-42c9-94d8-95c8674993eb
16/07/08 10:46:05 INFO HttpServer: Starting HTTP Server
16/07/08 10:46:05 INFO Utils: Successfully started service 'HTTP file server' on port 39558.
16/07/08 10:46:05 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/07/08 10:46:05 INFO SparkUI: Started SparkUI at http://192.168.59.131:4040
16/07/08 10:46:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/07/08 10:46:06 INFO Utils: Copying /home/student/Projects/hadoop-fundamentals/spark/sales.py to /tmp/spark-11ec83a1-cf85-4cf3-bac0-7ebc4dbf254d/sales.py
16/07/08 10:46:07 INFO SparkContext: Added file file:/home/student/Projects/hadoop-fundamentals/spark/sales.py at http://192.168.59.131:39558/files/sales.py with timestamp 1467999966974
16/07/08 10:46:07 INFO AkkaUtils: Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@192.168.59.131:60725/user/HeartbeatReceiver
16/07/08 10:46:07 INFO MemoryStore: ensureFreeSpace(163705) called with curMem=0, maxMem=280248975
16/07/08 10:46:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 159.9 KB, free 267.1 MB)
Traceback (most recent call last):
  File "/home/student/Projects/hadoop-fundamentals/spark/sales.py", line 60, in <module>
    months = months.reduceByKey(add)
  File "/srv/spark/python/pyspark/rdd.py", line 1375, in reduceByKey
    return self.combineByKey(lambda x: x, func, func, numPartitions)
  File "/srv/spark/python/pyspark/rdd.py", line 1564, in combineByKey
    numPartitions = self._defaultReducePartitions()
  File "/srv/spark/python/pyspark/rdd.py", line 1952, in _defaultReducePartitions
    return self.getNumPartitions()
  File "/srv/spark/python/pyspark/rdd.py", line 391, in getNumPartitions
    return self._jrdd.partitions().size()
  File "/srv/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/srv/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o36.partitions.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/home/student/Projects/hadoop-fundamentals/spark/shopping/orders.csv
    at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:285)
    at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
    at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:304)
    at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:179)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
    at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
    at org.apache.spark.api.python.PythonRDD.getPartitions(PythonRDD.scala:56)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
    at org.apache.spark.api.python.PythonRDD.getPartitions(PythonRDD.scala:56)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
    at org.apache.spark.api.java.JavaRDDLike$class.partitions(JavaRDDLike.scala:50)
    at org.apache.spark.api.java.JavaRDD.partitions(JavaRDD.scala:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
    at py4j.Gateway.invoke(Gateway.java:259)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:207)
    at java.lang.Thread.run(Thread.java:745)

student@hadoop:~/Projects/hadoop-fundamentals/spark$

**Comment by bbengfort** [comment]
Yeh, Spark errors are terrible, but this is a pretty simple one once you figure out how to weed out all the cruft: 

```
Input path does not exist: 
/home/student/Projects/hadoop-fundamentals/spark/shopping/orders.csv
```

So, it looks like you just need to unzip the orders.csv file and place it at that path, or you could modify sales.py with the path to the data set on disk. 

If you go to the "minimizing the verbosity of Spark" section in this post: https://districtdatalabs.silvrback.com/getting-started-with-spark-in-python -- hopefully that will help you clean up the massive amount of logging text that is spit out.
